name: "kitti360" #semantic motion labels
labels: # mit original IDs
  0: "unlabeled"
  1: "ego vehicle"
  2: "rectification border"
  3: "out of roi"
  4: "static"
  5: "dynamic"
  6: "ground"
  7: "road"
  8: "sidewalk"
  9: "parking"
  10: "rail track"
  11: "building"
  12: "wall"
  13: "fence"
  14: "guard rail"
  15: "bridge"
  16: "tunnel"
  17: "pole"
  18: "polegroup"
  19: "traffic light"
  20: "traffic sign"
  21: "vegetation"
  22: "terrain"
  23: "sky"
  24: "person"
  25: "rider"
  26: "car"
  27: "truck"
  28: "bus"
  29: "caravan"
  30: "trailer"
  31: "train"
  32: "motorcycle"
  33: "bicycle"
  34: "garage"
  35: "gate"
  36: "stop"
  37: "smallpole"
  38: "lamp"
  39: "trash bin"
  40: "vending machine"
  41: "box"
  42: "unknown construction"
  43: "unknown vehicle"
  44: "unknown object"
  -1: "license plate"
  200: "moving person"
  201: "moving rider"
  202: "moving car"
  203: "moving truck"
  204: "moving bus"
  205: "moving caravan"
  206: "moving trailer"
  207: "moving train"
  208: "moving motorcycle"
  209: "moving bicycle"
  210: "moving unknown vehicle"
color_map:
  0: [0, 0, 0]
  1: [0, 0, 0]
  2: [0, 0, 0]
  3: [0, 0, 0]
  4: [0, 0, 0]
  5: [111, 74, 0]
  6: [81, 0, 81]
  7: [128, 64, 128]
  8: [244, 35, 232]
  9: [250, 170, 160]
  10: [230, 150, 140]
  11: [70, 70, 70]
  12: [102, 102, 156]
  13: [190, 153, 153]
  14: [180, 165, 180]
  15: [150, 100, 100]
  16: [150, 120, 90]
  17: [153, 153, 153]
  18: [153, 153, 153]
  19: [250, 170, 30]
  20: [220, 220, 0]
  21: [107, 142, 35]
  22: [152, 251, 152]
  23: [70, 130, 180]
  24: [220, 20, 60]
  25: [255, 0, 0]
  26: [0, 0, 142]
  27: [0, 0, 70]
  28: [0, 60, 100]
  29: [0, 0, 90]
  30: [0, 0, 110]
  31: [0, 80, 100]
  32: [0, 0, 230]
  33: [119, 11, 32]
  34: [64, 128, 128]
  35: [190, 153, 153]
  36: [150, 120, 90]
  37: [153, 153, 153]
  38: [0, 64, 64]
  39: [0, 128, 192]
  40: [128, 64, 0]
  41: [64, 64, 128]
  42: [102, 0, 0]
  43: [51, 0, 51]
  44: [32, 32, 32]
  -1: [  0,  0,142]
  200: [ 0, 165, 255]
  201: [ 0, 165, 255]
  202: [ 0, 165, 255]
  203: [ 0, 165, 255]
  204: [ 0, 165, 255]
  205: [ 0, 165, 255]
  206: [ 0, 165, 255]
  207: [ 0, 165, 255]
  208: [ 0, 165, 255]
  209: [ 0, 165, 255]
  210: [ 0, 165, 255]
movable_classes:
  24: "person"
  25: "rider"
  26: "car"
  27: "truck"
  28: "bus"
  29: "caravan"
  30: "trailer"
  31: "train"
  32: "motorcycle"
  33: "bicycle"
  43: "unknown vehicle"
combine_mos_semantic_map:
  24: 200   #"person" to          "moving person"
  25: 201   #"rider" to           "moving rider"
  26: 202   #"car" to             "moving car"
  27: 203   #"truck" to           "moving truck"
  28: 204   #"bus" to             "moving bus"
  29: 205   #"caravan" to         "moving caravan"
  30: 206   #"trailer" to         "moving trailer"
  31: 207   #"train" to           "moving train"
  32: 208   #"motorcycle" to      "moving motorcycle"
  33: 209   #"bicycle" to         "moving bicycle"
  43: 210   #"unknown vehicle" to "moving unknown vehicle"
combine_mos_semantic_map_inv:
  200: 24   
  201: 25   
  202: 26   
  203: 27   
  204: 28   
  205: 29   
  206: 30   
  207: 31   
  208: 32   
  209: 33   
  210: 43   
split: #sequence number
  train: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  valid:
    - 8
  test:
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21