name: "kitti360" #even when working with KITTI odometry for inference use parser of KITTI-360
labels: # motion labels
  0: "unlabeled"
  1: "static"
  2: "dynamic"
color_map: # bgr
  0: [0, 0, 0]
  1: [255, 255, 255]
  2: [0, 0, 255]  
content: 
  0: 0.09155961468661394
  1: 0.9046922012140174
  2: 0.0037481840993687093
learning_map:
  0: 0
  1: 1
  2: 2
learning_map_inv:
  0: 0
  1: 1
  2: 2
learning_ignore:
  0: True     #'unlabeled'
  1: False    #'static'
  2: False    #'dynamic'
split: # sequence numbers
  train:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  valid:
    - 8
  test:
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    

    